### ISSUE TITLE
Add mathematical class

### ISSUE THREAD

**Issue by ptrdiff** [robot-lab/rcs-control-unit#49]
**Is your feature request related to a problem? Please describe.**
The control module works only with manipulators. It is impossible to translate generalized coordinates into world coordinates for different types of robots.

**Describe the solution you'd like**
Move the mathematical model of the manipulator from the computer vision module to the control module. Create mathematical class for telega.

**Comment by danila19991** [comment]
Math class was added. Need to mive manipulator model to it.

**Comment by danila19991** [comment]
Closed in #52
